TRUNCATE TABLE sport.team;

INSERT INTO sport.team (team_id,TEAM_NAME,SEASON,VALID_FROM,VALID_TO,MODIFIED_AT,CHANGED_BY) SELECT nextval('team_team_id_seq'),'Damen 30','Sommer 2020',TIMESTAMPTZ '2020-04-01 00:00:00',TIMESTAMPTZ '2020-09-20 00:00:00',CURRENT_TIMESTAMP,'Ben';
INSERT INTO sport.team (team_id,TEAM_NAME,SEASON,VALID_FROM,VALID_TO,MODIFIED_AT,CHANGED_BY) SELECT nextval('team_team_id_seq'),'Herren 30','Sommer 2020',TIMESTAMPTZ '2020-04-01 00:00:00',TIMESTAMPTZ '2020-09-20 00:00:00',CURRENT_TIMESTAMP,'Ben';
INSERT INTO sport.team (team_id,TEAM_NAME,SEASON,VALID_FROM,VALID_TO,MODIFIED_AT,CHANGED_BY) SELECT nextval('team_team_id_seq'),'Damen','Sommer 2020',TIMESTAMPTZ '2020-04-01 00:00:00',TIMESTAMPTZ '2020-09-20 00:00:00',CURRENT_TIMESTAMP,'Ben';
INSERT INTO sport.team (team_id,TEAM_NAME,SEASON,VALID_FROM,VALID_TO,MODIFIED_AT,CHANGED_BY) SELECT nextval('team_team_id_seq'),'Herren','Sommer 2020',TIMESTAMPTZ '2020-04-01 00:00:00',TIMESTAMPTZ '2020-09-20 00:00:00',CURRENT_TIMESTAMP,'Ben';
INSERT INTO sport.team (team_id,TEAM_NAME,SEASON,VALID_FROM,VALID_TO,MODIFIED_AT,CHANGED_BY) SELECT nextval('team_team_id_seq'),'Damen 30','Sommer 2021',TIMESTAMPTZ '2021-04-01 00:00:00',TIMESTAMPTZ '2021-09-22 00:00:00',CURRENT_TIMESTAMP,'Ben';

TRUNCATE TABLE club.person;
INSERT INTO club.person (PERSON_NO,IS_MEMBER,MEMBER_NO,FIRST_NAME,LAST_NAME) VALUES (1,TRUE,1,'Alexander','Satschko');
INSERT INTO club.person (PERSON_NO,IS_MEMBER,MEMBER_NO,FIRST_NAME,LAST_NAME) VALUES (2,TRUE,2,'Maximilian','Schmuck');
INSERT INTO club.person (PERSON_NO,IS_MEMBER,MEMBER_NO,FIRST_NAME,LAST_NAME) VALUES (3,TRUE,3,'Felix','Hutt');
INSERT INTO club.person (PERSON_NO,IS_MEMBER,MEMBER_NO,FIRST_NAME,LAST_NAME) VALUES (4,TRUE,4,'Marco','Mader');
INSERT INTO club.person (PERSON_NO,IS_MEMBER,MEMBER_NO,FIRST_NAME,LAST_NAME) VALUES (5,TRUE,5,'Christian','Blankl');
INSERT INTO club.person (PERSON_NO,IS_MEMBER,MEMBER_NO,FIRST_NAME,LAST_NAME) VALUES (6,TRUE,6,'Nikolas','Holzen');
INSERT INTO club.person (PERSON_NO,IS_MEMBER,MEMBER_NO,FIRST_NAME,LAST_NAME) VALUES (7,TRUE,7,'Florian','Grassl');
INSERT INTO club.person (PERSON_NO,IS_MEMBER,MEMBER_NO,FIRST_NAME,LAST_NAME) VALUES (8,TRUE,8,'Eddison','Ambarzumjan');
INSERT INTO club.person (PERSON_NO,IS_MEMBER,MEMBER_NO,FIRST_NAME,LAST_NAME) VALUES (9,TRUE,9,'Matvey','Khomentovsky');
INSERT INTO club.person (PERSON_NO,IS_MEMBER,MEMBER_NO,FIRST_NAME,LAST_NAME) VALUES (10,TRUE,10,'Konstantin','Barth');
INSERT INTO club.person (PERSON_NO,IS_MEMBER,MEMBER_NO,FIRST_NAME,LAST_NAME) VALUES (11,TRUE,11,'Lukas','Kortus');
INSERT INTO club.person (PERSON_NO,IS_MEMBER,MEMBER_NO,FIRST_NAME,LAST_NAME) VALUES (12,TRUE,12,'Simon','Walter');
INSERT INTO club.person (PERSON_NO,IS_MEMBER,MEMBER_NO,FIRST_NAME,LAST_NAME) VALUES (13,TRUE,13,'Nina','Späth');
INSERT INTO club.person (PERSON_NO,IS_MEMBER,MEMBER_NO,FIRST_NAME,LAST_NAME) VALUES (14,TRUE,14,'Julia','Prantl');
INSERT INTO club.person (PERSON_NO,IS_MEMBER,MEMBER_NO,FIRST_NAME,LAST_NAME) VALUES (15,TRUE,15,'Luba','Schifris');
INSERT INTO club.person (PERSON_NO,IS_MEMBER,MEMBER_NO,FIRST_NAME,LAST_NAME) VALUES (16,TRUE,16,'Sonja','Nikolic');
INSERT INTO club.person (PERSON_NO,IS_MEMBER,MEMBER_NO,FIRST_NAME,LAST_NAME) VALUES (17,TRUE,17,'Karola','Thumm');
INSERT INTO club.person (PERSON_NO,IS_MEMBER,MEMBER_NO,FIRST_NAME,LAST_NAME) VALUES (18,TRUE,18,'Astrid','Obermeier');
INSERT INTO club.person (PERSON_NO,IS_MEMBER,MEMBER_NO,FIRST_NAME,LAST_NAME) VALUES (19,TRUE,19,'Nina','Killi');
INSERT INTO club.person (PERSON_NO,IS_MEMBER,MEMBER_NO,FIRST_NAME,LAST_NAME) VALUES (20,TRUE,20,'Marie','Wolter');
INSERT INTO club.person (PERSON_NO,IS_MEMBER,MEMBER_NO,FIRST_NAME,LAST_NAME) VALUES (21,TRUE,21,'Carolin','Ganahl');
INSERT INTO club.person (PERSON_NO,IS_MEMBER,MEMBER_NO,FIRST_NAME,LAST_NAME) VALUES (22,TRUE,22,'Frizzi','Mayer');
INSERT INTO club.person (PERSON_NO,IS_MEMBER,MEMBER_NO,FIRST_NAME,LAST_NAME) VALUES (23,TRUE,23,'Theresa','Hirle');
INSERT INTO club.person (PERSON_NO,IS_MEMBER,MEMBER_NO,FIRST_NAME,LAST_NAME) VALUES (24,TRUE,24,'Janina','Evers');
INSERT INTO club.person (PERSON_NO,IS_MEMBER,MEMBER_NO,FIRST_NAME,LAST_NAME) VALUES (25,TRUE,25,'Susanna','Strauß');




truncate table sport.player;
INSERT INTO sport.player (MEMBER_NO) VALUES (1);
INSERT INTO sport.player (MEMBER_NO) VALUES (2);
INSERT INTO sport.player (MEMBER_NO) VALUES (3);
INSERT INTO sport.player (MEMBER_NO) VALUES (4);
INSERT INTO sport.player (MEMBER_NO) VALUES (5);
INSERT INTO sport.player (MEMBER_NO) VALUES (6);
INSERT INTO sport.player (MEMBER_NO) VALUES (7);
INSERT INTO sport.player (MEMBER_NO) VALUES (8);
INSERT INTO sport.player (MEMBER_NO) VALUES (9);
INSERT INTO sport.player (MEMBER_NO) VALUES (10);
INSERT INTO sport.player (MEMBER_NO) VALUES (11);
INSERT INTO sport.player (MEMBER_NO) VALUES (12);
INSERT INTO sport.player (MEMBER_NO) VALUES (13);
INSERT INTO sport.player (MEMBER_NO) VALUES (14);
INSERT INTO sport.player (MEMBER_NO) VALUES (15);
INSERT INTO sport.player (MEMBER_NO) VALUES (16);
INSERT INTO sport.player (MEMBER_NO) VALUES (17);
INSERT INTO sport.player (MEMBER_NO) VALUES (18);
INSERT INTO sport.player (MEMBER_NO) VALUES (19);
INSERT INTO sport.player (MEMBER_NO) VALUES (20);
INSERT INTO sport.player (MEMBER_NO) VALUES (21);
INSERT INTO sport.player (MEMBER_NO) VALUES (22);
INSERT INTO sport.player (MEMBER_NO) VALUES (23);
INSERT INTO sport.player (MEMBER_NO) VALUES (24);
INSERT INTO sport.player (MEMBER_NO) VALUES (25);


truncate table sport.team_members;
WITH team as (SELECT TEAM_ID,1 as MEMBER_NO FROM sport.team WHERE 1=1 AND TEAM_NAME='Herren 30' AND SEASON='Sommer 2020'), player as (SELECT PLAYER_ID,1 as member_no FROM sport.player WHERE 1=1 AND MEMBER_NO=1) INSERT INTO sport.team_members (TEAM_ID,PLAYER_ID,IS_MAIN_TEAM) SELECT team.TEAM_ID,player.PLAYER_ID,TRUE FROM team RIGHT JOIN player ON team.MEMBER_NO=player.MEMBER_NO;
WITH team as (SELECT TEAM_ID,2 as MEMBER_NO FROM sport.team WHERE 1=1 AND TEAM_NAME='Herren 30' AND SEASON='Sommer 2020'), player as (SELECT PLAYER_ID,2 as member_no FROM sport.player WHERE 1=1 AND MEMBER_NO=2) INSERT INTO sport.team_members (TEAM_ID,PLAYER_ID,IS_MAIN_TEAM) SELECT team.TEAM_ID,player.PLAYER_ID,TRUE FROM team RIGHT JOIN player ON team.MEMBER_NO=player.MEMBER_NO;
WITH team as (SELECT TEAM_ID,3 as MEMBER_NO FROM sport.team WHERE 1=1 AND TEAM_NAME='Herren 30' AND SEASON='Sommer 2020'), player as (SELECT PLAYER_ID,3 as member_no FROM sport.player WHERE 1=1 AND MEMBER_NO=3) INSERT INTO sport.team_members (TEAM_ID,PLAYER_ID,IS_MAIN_TEAM) SELECT team.TEAM_ID,player.PLAYER_ID,TRUE FROM team RIGHT JOIN player ON team.MEMBER_NO=player.MEMBER_NO;
WITH team as (SELECT TEAM_ID,4 as MEMBER_NO FROM sport.team WHERE 1=1 AND TEAM_NAME='Herren 30' AND SEASON='Sommer 2020'), player as (SELECT PLAYER_ID,4 as member_no FROM sport.player WHERE 1=1 AND MEMBER_NO=4) INSERT INTO sport.team_members (TEAM_ID,PLAYER_ID,IS_MAIN_TEAM) SELECT team.TEAM_ID,player.PLAYER_ID,TRUE FROM team RIGHT JOIN player ON team.MEMBER_NO=player.MEMBER_NO;
WITH team as (SELECT TEAM_ID,5 as MEMBER_NO FROM sport.team WHERE 1=1 AND TEAM_NAME='Herren 30' AND SEASON='Sommer 2020'), player as (SELECT PLAYER_ID,5 as member_no FROM sport.player WHERE 1=1 AND MEMBER_NO=5) INSERT INTO sport.team_members (TEAM_ID,PLAYER_ID,IS_MAIN_TEAM) SELECT team.TEAM_ID,player.PLAYER_ID,TRUE FROM team RIGHT JOIN player ON team.MEMBER_NO=player.MEMBER_NO;
WITH team as (SELECT TEAM_ID,6 as MEMBER_NO FROM sport.team WHERE 1=1 AND TEAM_NAME='Herren 30' AND SEASON='Sommer 2020'), player as (SELECT PLAYER_ID,6 as member_no FROM sport.player WHERE 1=1 AND MEMBER_NO=6) INSERT INTO sport.team_members (TEAM_ID,PLAYER_ID,IS_MAIN_TEAM) SELECT team.TEAM_ID,player.PLAYER_ID,TRUE FROM team RIGHT JOIN player ON team.MEMBER_NO=player.MEMBER_NO;
WITH team as (SELECT TEAM_ID,7 as MEMBER_NO FROM sport.team WHERE 1=1 AND TEAM_NAME='Herren' AND SEASON='Sommer 2020'), player as (SELECT PLAYER_ID,7 as member_no FROM sport.player WHERE 1=1 AND MEMBER_NO=7) INSERT INTO sport.team_members (TEAM_ID,PLAYER_ID,IS_MAIN_TEAM) SELECT team.TEAM_ID,player.PLAYER_ID,TRUE FROM team RIGHT JOIN player ON team.MEMBER_NO=player.MEMBER_NO;
WITH team as (SELECT TEAM_ID,8 as MEMBER_NO FROM sport.team WHERE 1=1 AND TEAM_NAME='Herren' AND SEASON='Sommer 2020'), player as (SELECT PLAYER_ID,8 as member_no FROM sport.player WHERE 1=1 AND MEMBER_NO=8) INSERT INTO sport.team_members (TEAM_ID,PLAYER_ID,IS_MAIN_TEAM) SELECT team.TEAM_ID,player.PLAYER_ID,TRUE FROM team RIGHT JOIN player ON team.MEMBER_NO=player.MEMBER_NO;
WITH team as (SELECT TEAM_ID,9 as MEMBER_NO FROM sport.team WHERE 1=1 AND TEAM_NAME='Herren' AND SEASON='Sommer 2020'), player as (SELECT PLAYER_ID,9 as member_no FROM sport.player WHERE 1=1 AND MEMBER_NO=9) INSERT INTO sport.team_members (TEAM_ID,PLAYER_ID,IS_MAIN_TEAM) SELECT team.TEAM_ID,player.PLAYER_ID,TRUE FROM team RIGHT JOIN player ON team.MEMBER_NO=player.MEMBER_NO;
WITH team as (SELECT TEAM_ID,10 as MEMBER_NO FROM sport.team WHERE 1=1 AND TEAM_NAME='Herren' AND SEASON='Sommer 2020'), player as (SELECT PLAYER_ID,10 as member_no FROM sport.player WHERE 1=1 AND MEMBER_NO=10) INSERT INTO sport.team_members (TEAM_ID,PLAYER_ID,IS_MAIN_TEAM) SELECT team.TEAM_ID,player.PLAYER_ID,TRUE FROM team RIGHT JOIN player ON team.MEMBER_NO=player.MEMBER_NO;
WITH team as (SELECT TEAM_ID,11 as MEMBER_NO FROM sport.team WHERE 1=1 AND TEAM_NAME='Herren' AND SEASON='Sommer 2020'), player as (SELECT PLAYER_ID,11 as member_no FROM sport.player WHERE 1=1 AND MEMBER_NO=11) INSERT INTO sport.team_members (TEAM_ID,PLAYER_ID,IS_MAIN_TEAM) SELECT team.TEAM_ID,player.PLAYER_ID,TRUE FROM team RIGHT JOIN player ON team.MEMBER_NO=player.MEMBER_NO;
WITH team as (SELECT TEAM_ID,12 as MEMBER_NO FROM sport.team WHERE 1=1 AND TEAM_NAME='Herren' AND SEASON='Sommer 2020'), player as (SELECT PLAYER_ID,12 as member_no FROM sport.player WHERE 1=1 AND MEMBER_NO=12) INSERT INTO sport.team_members (TEAM_ID,PLAYER_ID,IS_MAIN_TEAM) SELECT team.TEAM_ID,player.PLAYER_ID,TRUE FROM team RIGHT JOIN player ON team.MEMBER_NO=player.MEMBER_NO;
WITH team as (SELECT TEAM_ID,13 as MEMBER_NO FROM sport.team WHERE 1=1 AND TEAM_NAME='Damen 30' AND SEASON='Sommer 2020'), player as (SELECT PLAYER_ID,13 as member_no FROM sport.player WHERE 1=1 AND MEMBER_NO=13) INSERT INTO sport.team_members (TEAM_ID,PLAYER_ID,IS_MAIN_TEAM) SELECT team.TEAM_ID,player.PLAYER_ID,TRUE FROM team RIGHT JOIN player ON team.MEMBER_NO=player.MEMBER_NO;
WITH team as (SELECT TEAM_ID,14 as MEMBER_NO FROM sport.team WHERE 1=1 AND TEAM_NAME='Damen 30' AND SEASON='Sommer 2020'), player as (SELECT PLAYER_ID,14 as member_no FROM sport.player WHERE 1=1 AND MEMBER_NO=14) INSERT INTO sport.team_members (TEAM_ID,PLAYER_ID,IS_MAIN_TEAM) SELECT team.TEAM_ID,player.PLAYER_ID,TRUE FROM team RIGHT JOIN player ON team.MEMBER_NO=player.MEMBER_NO;
WITH team as (SELECT TEAM_ID,15 as MEMBER_NO FROM sport.team WHERE 1=1 AND TEAM_NAME='Damen 30' AND SEASON='Sommer 2020'), player as (SELECT PLAYER_ID,15 as member_no FROM sport.player WHERE 1=1 AND MEMBER_NO=15) INSERT INTO sport.team_members (TEAM_ID,PLAYER_ID,IS_MAIN_TEAM) SELECT team.TEAM_ID,player.PLAYER_ID,TRUE FROM team RIGHT JOIN player ON team.MEMBER_NO=player.MEMBER_NO;
WITH team as (SELECT TEAM_ID,16 as MEMBER_NO FROM sport.team WHERE 1=1 AND TEAM_NAME='Damen 30' AND SEASON='Sommer 2020'), player as (SELECT PLAYER_ID,16 as member_no FROM sport.player WHERE 1=1 AND MEMBER_NO=16) INSERT INTO sport.team_members (TEAM_ID,PLAYER_ID,IS_MAIN_TEAM) SELECT team.TEAM_ID,player.PLAYER_ID,TRUE FROM team RIGHT JOIN player ON team.MEMBER_NO=player.MEMBER_NO;
WITH team as (SELECT TEAM_ID,17 as MEMBER_NO FROM sport.team WHERE 1=1 AND TEAM_NAME='Damen 30' AND SEASON='Sommer 2020'), player as (SELECT PLAYER_ID,17 as member_no FROM sport.player WHERE 1=1 AND MEMBER_NO=17) INSERT INTO sport.team_members (TEAM_ID,PLAYER_ID,IS_MAIN_TEAM) SELECT team.TEAM_ID,player.PLAYER_ID,TRUE FROM team RIGHT JOIN player ON team.MEMBER_NO=player.MEMBER_NO;
WITH team as (SELECT TEAM_ID,18 as MEMBER_NO FROM sport.team WHERE 1=1 AND TEAM_NAME='Damen 30' AND SEASON='Sommer 2020'), player as (SELECT PLAYER_ID,18 as member_no FROM sport.player WHERE 1=1 AND MEMBER_NO=18) INSERT INTO sport.team_members (TEAM_ID,PLAYER_ID,IS_MAIN_TEAM) SELECT team.TEAM_ID,player.PLAYER_ID,TRUE FROM team RIGHT JOIN player ON team.MEMBER_NO=player.MEMBER_NO;
WITH team as (SELECT TEAM_ID,19 as MEMBER_NO FROM sport.team WHERE 1=1 AND TEAM_NAME='Damen 30' AND SEASON='Sommer 2020'), player as (SELECT PLAYER_ID,19 as member_no FROM sport.player WHERE 1=1 AND MEMBER_NO=19) INSERT INTO sport.team_members (TEAM_ID,PLAYER_ID,IS_MAIN_TEAM) SELECT team.TEAM_ID,player.PLAYER_ID,TRUE FROM team RIGHT JOIN player ON team.MEMBER_NO=player.MEMBER_NO;
WITH team as (SELECT TEAM_ID,20 as MEMBER_NO FROM sport.team WHERE 1=1 AND TEAM_NAME='Damen' AND SEASON='Sommer 2020'), player as (SELECT PLAYER_ID,20 as member_no FROM sport.player WHERE 1=1 AND MEMBER_NO=20) INSERT INTO sport.team_members (TEAM_ID,PLAYER_ID,IS_MAIN_TEAM) SELECT team.TEAM_ID,player.PLAYER_ID,TRUE FROM team RIGHT JOIN player ON team.MEMBER_NO=player.MEMBER_NO;
WITH team as (SELECT TEAM_ID,13 as MEMBER_NO FROM sport.team WHERE 1=1 AND TEAM_NAME='Damen 30' AND SEASON='Sommer 2021'), player as (SELECT PLAYER_ID,13 as member_no FROM sport.player WHERE 1=1 AND MEMBER_NO=13) INSERT INTO sport.team_members (TEAM_ID,PLAYER_ID,IS_MAIN_TEAM) SELECT team.TEAM_ID,player.PLAYER_ID,TRUE FROM team RIGHT JOIN player ON team.MEMBER_NO=player.MEMBER_NO;
WITH team as (SELECT TEAM_ID,14 as MEMBER_NO FROM sport.team WHERE 1=1 AND TEAM_NAME='Damen 30' AND SEASON='Sommer 2021'), player as (SELECT PLAYER_ID,14 as member_no FROM sport.player WHERE 1=1 AND MEMBER_NO=14) INSERT INTO sport.team_members (TEAM_ID,PLAYER_ID,IS_MAIN_TEAM) SELECT team.TEAM_ID,player.PLAYER_ID,TRUE FROM team RIGHT JOIN player ON team.MEMBER_NO=player.MEMBER_NO;
WITH team as (SELECT TEAM_ID,15 as MEMBER_NO FROM sport.team WHERE 1=1 AND TEAM_NAME='Damen 30' AND SEASON='Sommer 2021'), player as (SELECT PLAYER_ID,15 as member_no FROM sport.player WHERE 1=1 AND MEMBER_NO=15) INSERT INTO sport.team_members (TEAM_ID,PLAYER_ID,IS_MAIN_TEAM) SELECT team.TEAM_ID,player.PLAYER_ID,TRUE FROM team RIGHT JOIN player ON team.MEMBER_NO=player.MEMBER_NO;
WITH team as (SELECT TEAM_ID,16 as MEMBER_NO FROM sport.team WHERE 1=1 AND TEAM_NAME='Damen 30' AND SEASON='Sommer 2021'), player as (SELECT PLAYER_ID,16 as member_no FROM sport.player WHERE 1=1 AND MEMBER_NO=16) INSERT INTO sport.team_members (TEAM_ID,PLAYER_ID,IS_MAIN_TEAM) SELECT team.TEAM_ID,player.PLAYER_ID,TRUE FROM team RIGHT JOIN player ON team.MEMBER_NO=player.MEMBER_NO;
WITH team as (SELECT TEAM_ID,17 as MEMBER_NO FROM sport.team WHERE 1=1 AND TEAM_NAME='Damen 30' AND SEASON='Sommer 2021'), player as (SELECT PLAYER_ID,17 as member_no FROM sport.player WHERE 1=1 AND MEMBER_NO=17) INSERT INTO sport.team_members (TEAM_ID,PLAYER_ID,IS_MAIN_TEAM) SELECT team.TEAM_ID,player.PLAYER_ID,TRUE FROM team RIGHT JOIN player ON team.MEMBER_NO=player.MEMBER_NO;
WITH team as (SELECT TEAM_ID,18 as MEMBER_NO FROM sport.team WHERE 1=1 AND TEAM_NAME='Damen 30' AND SEASON='Sommer 2021'), player as (SELECT PLAYER_ID,18 as member_no FROM sport.player WHERE 1=1 AND MEMBER_NO=18) INSERT INTO sport.team_members (TEAM_ID,PLAYER_ID,IS_MAIN_TEAM) SELECT team.TEAM_ID,player.PLAYER_ID,TRUE FROM team RIGHT JOIN player ON team.MEMBER_NO=player.MEMBER_NO;
WITH team as (SELECT TEAM_ID,19 as MEMBER_NO FROM sport.team WHERE 1=1 AND TEAM_NAME='Damen 30' AND SEASON='Sommer 2021'), player as (SELECT PLAYER_ID,19 as member_no FROM sport.player WHERE 1=1 AND MEMBER_NO=19) INSERT INTO sport.team_members (TEAM_ID,PLAYER_ID,IS_MAIN_TEAM) SELECT team.TEAM_ID,player.PLAYER_ID,TRUE FROM team RIGHT JOIN player ON team.MEMBER_NO=player.MEMBER_NO;
WITH team as (SELECT TEAM_ID,21 as MEMBER_NO FROM sport.team WHERE 1=1 AND TEAM_NAME='Damen' AND SEASON='Sommer 2020'), player as (SELECT PLAYER_ID,21 as member_no FROM sport.player WHERE 1=1 AND MEMBER_NO=21) INSERT INTO sport.team_members (TEAM_ID,PLAYER_ID,IS_MAIN_TEAM) SELECT team.TEAM_ID,player.PLAYER_ID,TRUE FROM team RIGHT JOIN player ON team.MEMBER_NO=player.MEMBER_NO;
WITH team as (SELECT TEAM_ID,22 as MEMBER_NO FROM sport.team WHERE 1=1 AND TEAM_NAME='Damen' AND SEASON='Sommer 2020'), player as (SELECT PLAYER_ID,22 as member_no FROM sport.player WHERE 1=1 AND MEMBER_NO=22) INSERT INTO sport.team_members (TEAM_ID,PLAYER_ID,IS_MAIN_TEAM) SELECT team.TEAM_ID,player.PLAYER_ID,TRUE FROM team RIGHT JOIN player ON team.MEMBER_NO=player.MEMBER_NO;
WITH team as (SELECT TEAM_ID,23 as MEMBER_NO FROM sport.team WHERE 1=1 AND TEAM_NAME='Damen' AND SEASON='Sommer 2020'), player as (SELECT PLAYER_ID,23 as member_no FROM sport.player WHERE 1=1 AND MEMBER_NO=23) INSERT INTO sport.team_members (TEAM_ID,PLAYER_ID,IS_MAIN_TEAM) SELECT team.TEAM_ID,player.PLAYER_ID,TRUE FROM team RIGHT JOIN player ON team.MEMBER_NO=player.MEMBER_NO;
WITH team as (SELECT TEAM_ID,24 as MEMBER_NO FROM sport.team WHERE 1=1 AND TEAM_NAME='Damen' AND SEASON='Sommer 2020'), player as (SELECT PLAYER_ID,24 as member_no FROM sport.player WHERE 1=1 AND MEMBER_NO=24) INSERT INTO sport.team_members (TEAM_ID,PLAYER_ID,IS_MAIN_TEAM) SELECT team.TEAM_ID,player.PLAYER_ID,TRUE FROM team RIGHT JOIN player ON team.MEMBER_NO=player.MEMBER_NO;
WITH team as (SELECT TEAM_ID,25 as MEMBER_NO FROM sport.team WHERE 1=1 AND TEAM_NAME='Damen' AND SEASON='Sommer 2020'), player as (SELECT PLAYER_ID,25 as member_no FROM sport.player WHERE 1=1 AND MEMBER_NO=25) INSERT INTO sport.team_members (TEAM_ID,PLAYER_ID,IS_MAIN_TEAM) SELECT team.TEAM_ID,player.PLAYER_ID,TRUE FROM team RIGHT JOIN player ON team.MEMBER_NO=player.MEMBER_NO;

truncate table sport.benefit;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Damen 30' AND SEASON='Sommer 2020') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 3,help.entity_id,'team','Damen 30 Trainerdoppelstunde Winter 2019/2020',2,TIMESTAMPTZ '2019-09-21 00:00:00',TIMESTAMPTZ '2020-04-01 00:00:00',50,1,44,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Damen 30' AND SEASON='Sommer 2020') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 3,help.entity_id,'team','Damen 30 Trainerstunde Sommer 2020',2,TIMESTAMPTZ '2020-04-01 00:00:00',TIMESTAMPTZ '2020-09-22 00:00:00',11,1,44,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Damen 30' AND SEASON='Sommer 2021') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 3,help.entity_id,'team','Damen 30 Trainerstunde Winter 2020/2021',2,TIMESTAMPTZ '2020-09-22 00:00:00',TIMESTAMPTZ '2021-04-01 00:00:00',25,1,44,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Damen 30' AND SEASON='Sommer 2020') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 2,help.entity_id,'team','Damen 30 Dienstag Doppelstunde Halle Winter 2019/2020',3,TIMESTAMPTZ '2019-09-21 00:00:00',TIMESTAMPTZ '2020-04-01 00:00:00',2,4,586,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Damen 30' AND SEASON='Sommer 2021') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 2,help.entity_id,'team','Damen 30 Dienstag Doppelstunde Halle Winter 2020/2021',3,TIMESTAMPTZ '2020-09-22 00:00:00',TIMESTAMPTZ '2021-04-01 00:00:00',2,4,586,NULL,FALSE FROM help;
WITH help as (SELECT pl.player_id as entity_id from sport.player pl LEFT JOIN club.person pe ON pl.member_no = pe.member_no WHERE 1=1 AND pe.FIRST_NAME='Nina' AND pe.LAST_NAME='Späth') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 7,help.entity_id,'player','Aufwandsentschädigung',1,TIMESTAMPTZ '2020-05-01 00:00:00',TIMESTAMPTZ '2020-09-01 00:00:00',1,3,190,NULL,FALSE FROM help;
WITH help as (SELECT pl.player_id as entity_id from sport.player pl LEFT JOIN club.person pe ON pl.member_no = pe.member_no WHERE 1=1 AND pe.FIRST_NAME='Nina' AND pe.LAST_NAME='Killi') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 7,help.entity_id,'player','Aufwandsentschädigung',1,TIMESTAMPTZ '2020-05-01 00:00:00',TIMESTAMPTZ '2020-09-01 00:00:00',1,3,190,NULL,FALSE FROM help;
WITH help as (SELECT pl.player_id as entity_id from sport.player pl LEFT JOIN club.person pe ON pl.member_no = pe.member_no WHERE 1=1 AND pe.FIRST_NAME='Julia' AND pe.LAST_NAME='Prantl') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 7,help.entity_id,'player','Aufwandsentschädigung',1,TIMESTAMPTZ '2020-05-01 00:00:00',TIMESTAMPTZ '2020-09-01 00:00:00',1,3,190,NULL,FALSE FROM help;
WITH help as (SELECT pl.player_id as entity_id from sport.player pl LEFT JOIN club.person pe ON pl.member_no = pe.member_no WHERE 1=1 AND pe.FIRST_NAME='Nina' AND pe.LAST_NAME='Späth') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 7,help.entity_id,'player','Aufwandsentschädigung',1,TIMESTAMPTZ '2019-05-01 00:00:00',TIMESTAMPTZ '2019-09-01 00:00:00',1,3,190,NULL,FALSE FROM help;
WITH help as (SELECT pl.player_id as entity_id from sport.player pl LEFT JOIN club.person pe ON pl.member_no = pe.member_no WHERE 1=1 AND pe.FIRST_NAME='Julia' AND pe.LAST_NAME='Prantl') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 7,help.entity_id,'player','Aufwandsentschädigung',1,TIMESTAMPTZ '2019-05-01 00:00:00',TIMESTAMPTZ '2019-09-01 00:00:00',1,3,190,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Damen 30' AND SEASON='Sommer 2021') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 3,help.entity_id,'team','Trainingsbälle',2,TIMESTAMPTZ '2019-09-21 00:00:00',TIMESTAMPTZ '2020-09-22 00:00:00',18,2,7,NULL,FALSE FROM help;
WITH help as (SELECT pl.player_id as entity_id from sport.player pl LEFT JOIN club.person pe ON pl.member_no = pe.member_no WHERE 1=1 AND pe.FIRST_NAME='Karola' AND pe.LAST_NAME='Thumm') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 7,help.entity_id,'player','Aufwandsentschädigung',1,TIMESTAMPTZ '2020-05-01 00:00:00',TIMESTAMPTZ '2020-09-01 00:00:00',1,3,190,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Damen 30' AND SEASON='Sommer 2020') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 2,help.entity_id,'team','Damen 30 Samstag Doppelstunde Halle Winter 2019/2020',3,TIMESTAMPTZ '2019-09-21 00:00:00',TIMESTAMPTZ '2020-04-01 00:00:00',2,4,482,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Damen 30' AND SEASON='Sommer 2021') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 2,help.entity_id,'team','Damen 30 Samstag Doppelstunde Halle Winter 2020/2021',3,TIMESTAMPTZ '2020-09-22 00:00:00',TIMESTAMPTZ '2021-04-01 00:00:00',2,4,482,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Herren' AND SEASON='Sommer 2020') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 2,help.entity_id,'team','Herren Samstag Doppelstunde Halle Winter 2019/2020',3,TIMESTAMPTZ '2019-09-21 00:00:00',TIMESTAMPTZ '2020-04-01 00:00:00',2,4,482,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Herren' AND SEASON='Sommer 2021') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 2,help.entity_id,'team','Herren Samstag Doppelstunde Halle Winter 2020/2021',3,TIMESTAMPTZ '2020-09-22 00:00:00',TIMESTAMPTZ '2021-04-01 00:00:00',2,4,482,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Damen' AND SEASON='Sommer 2020') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 2,help.entity_id,'team','Damen Samstag Doppelstunde Halle Winter 2019/2020',3,TIMESTAMPTZ '2019-09-21 00:00:00',TIMESTAMPTZ '2020-04-01 00:00:00',2,4,482,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Damen' AND SEASON='Sommer 2021') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 2,help.entity_id,'team','Damen Samstag Doppelstunde Halle Winter 2020/2021',3,TIMESTAMPTZ '2020-09-22 00:00:00',TIMESTAMPTZ '2021-04-01 00:00:00',2,4,482,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Herren 30' AND SEASON='Sommer 2020') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 2,help.entity_id,'team','Herren 30 Samstag Doppelstunde Halle Winter 2019/2020',3,TIMESTAMPTZ '2019-09-21 00:00:00',TIMESTAMPTZ '2020-04-01 00:00:00',2,4,482,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Herren 30' AND SEASON='Sommer 2021') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 2,help.entity_id,'team','Herren 30 Samstag Doppelstunde Halle Winter 2020/2021',3,TIMESTAMPTZ '2020-09-22 00:00:00',TIMESTAMPTZ '2021-04-01 00:00:00',2,4,482,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Herren 30' AND SEASON='Sommer 2020') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 2,help.entity_id,'team','Herren 30 Dienstag Doppelstunde Halle Winter 2019/2020',3,TIMESTAMPTZ '2019-09-21 00:00:00',TIMESTAMPTZ '2020-04-01 00:00:00',2,4,586,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Herren 30' AND SEASON='Sommer 2021') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 2,help.entity_id,'team','Herren 30 Dienstag Doppelstunde Halle Winter 2020/2021',3,TIMESTAMPTZ '2020-09-22 00:00:00',TIMESTAMPTZ '2021-04-01 00:00:00',2,4,586,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Damen' AND SEASON='Sommer 2020') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 2,help.entity_id,'team','Damen Dienstag Doppelstunde Halle Winter 2019/2020',3,TIMESTAMPTZ '2019-09-21 00:00:00',TIMESTAMPTZ '2020-04-01 00:00:00',2,4,586,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Damen' AND SEASON='Sommer 2021') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 2,help.entity_id,'team','Damen Dienstag Doppelstunde Halle Winter 2020/2021',3,TIMESTAMPTZ '2020-09-22 00:00:00',TIMESTAMPTZ '2021-04-01 00:00:00',2,4,586,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Herren' AND SEASON='Sommer 2020') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 2,help.entity_id,'team','Herren Dienstag Doppelstunde Halle Winter 2019/2020',3,TIMESTAMPTZ '2019-09-21 00:00:00',TIMESTAMPTZ '2020-04-01 00:00:00',2,4,586,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Herren' AND SEASON='Sommer 2021') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 2,help.entity_id,'team','Herren Dienstag Doppelstunde Halle Winter 2020/2021',3,TIMESTAMPTZ '2020-09-22 00:00:00',TIMESTAMPTZ '2021-04-01 00:00:00',2,4,586,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Herren' AND SEASON='Sommer 2020') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 3,help.entity_id,'team','Herren Trainerdoppelstunde Winter 2019/2020',2,TIMESTAMPTZ '2019-09-21 00:00:00',TIMESTAMPTZ '2020-04-01 00:00:00',50,1,10,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Herren' AND SEASON='Sommer 2020') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 3,help.entity_id,'team','Herren Trainerdoppelstunde Sommer 2020',2,TIMESTAMPTZ '2020-04-01 00:00:00',TIMESTAMPTZ '2020-09-22 00:00:00',22,1,10,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Herren' AND SEASON='Sommer 2021') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 3,help.entity_id,'team','Herren Trainerdoppelstunde Winter 2020/2021',2,TIMESTAMPTZ '2020-09-22 00:00:00',TIMESTAMPTZ '2021-04-01 00:00:00',50,1,10,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Herren 30' AND SEASON='Sommer 2020') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 3,help.entity_id,'team','Herren 30 Trainerdoppelstunde Winter 2019/2020',2,TIMESTAMPTZ '2019-09-21 00:00:00',TIMESTAMPTZ '2020-04-01 00:00:00',50,1,10,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Herren 30' AND SEASON='Sommer 2020') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 3,help.entity_id,'team','Herren 30 Trainerdoppelstunde Sommer 2020',2,TIMESTAMPTZ '2020-04-01 00:00:00',TIMESTAMPTZ '2020-09-22 00:00:00',22,1,10,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Herren 30' AND SEASON='Sommer 2021') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 3,help.entity_id,'team','Herren 30 Trainerdoppelstunde Winter 2020/2021',2,TIMESTAMPTZ '2020-09-22 00:00:00',TIMESTAMPTZ '2021-04-01 00:00:00',50,1,10,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Herren 30' AND SEASON='Sommer 2021') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 3,help.entity_id,'team','Trainingsbälle',2,TIMESTAMPTZ '2019-09-21 00:00:00',TIMESTAMPTZ '2020-09-22 00:00:00',18,2,6.9,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Herren' AND SEASON='Sommer 2021') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 3,help.entity_id,'team','Trainingsbälle',2,TIMESTAMPTZ '2019-09-21 00:00:00',TIMESTAMPTZ '2020-09-22 00:00:00',18,2,6.9,NULL,FALSE FROM help;
WITH help as (SELECT pl.player_id as entity_id from sport.player pl LEFT JOIN club.person pe ON pl.member_no = pe.member_no WHERE 1=1 AND pe.FIRST_NAME='Simon' AND pe.LAST_NAME='Walter') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 7,help.entity_id,'player','Aufwandsentschädigung',1,TIMESTAMPTZ '2019-05-01 00:00:00',TIMESTAMPTZ '2019-09-01 00:00:00',1,3,190,NULL,FALSE FROM help;
WITH help as (SELECT pl.player_id as entity_id from sport.player pl LEFT JOIN club.person pe ON pl.member_no = pe.member_no WHERE 1=1 AND pe.FIRST_NAME='Simon' AND pe.LAST_NAME='Walter') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 7,help.entity_id,'player','Aufwandsentschädigung',1,TIMESTAMPTZ '2020-05-01 00:00:00',TIMESTAMPTZ '2020-09-01 00:00:00',1,3,190,NULL,FALSE FROM help;
WITH help as (SELECT pl.player_id as entity_id from sport.player pl LEFT JOIN club.person pe ON pl.member_no = pe.member_no WHERE 1=1 AND pe.FIRST_NAME='Konstantin' AND pe.LAST_NAME='Barth') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 7,help.entity_id,'player','Aufwandsentschädigung',1,TIMESTAMPTZ '2019-05-01 00:00:00',TIMESTAMPTZ '2019-09-01 00:00:00',1,3,190,NULL,FALSE FROM help;
WITH help as (SELECT pl.player_id as entity_id from sport.player pl LEFT JOIN club.person pe ON pl.member_no = pe.member_no WHERE 1=1 AND pe.FIRST_NAME='Konstantin' AND pe.LAST_NAME='Barth') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 7,help.entity_id,'player','Aufwandsentschädigung',1,TIMESTAMPTZ '2020-05-01 00:00:00',TIMESTAMPTZ '2020-09-01 00:00:00',1,3,190,NULL,FALSE FROM help;
WITH help as (SELECT pl.player_id as entity_id from sport.player pl LEFT JOIN club.person pe ON pl.member_no = pe.member_no WHERE 1=1 AND pe.FIRST_NAME='Florian' AND pe.LAST_NAME='Grassl') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 7,help.entity_id,'player','Aufwandsentschädigung',1,TIMESTAMPTZ '2019-05-01 00:00:00',TIMESTAMPTZ '2019-09-01 00:00:00',1,3,190,NULL,FALSE FROM help;
WITH help as (SELECT pl.player_id as entity_id from sport.player pl LEFT JOIN club.person pe ON pl.member_no = pe.member_no WHERE 1=1 AND pe.FIRST_NAME='Florian' AND pe.LAST_NAME='Grassl') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 7,help.entity_id,'player','Aufwandsentschädigung',1,TIMESTAMPTZ '2020-05-01 00:00:00',TIMESTAMPTZ '2020-09-01 00:00:00',1,3,190,NULL,FALSE FROM help;
WITH help as (SELECT pl.player_id as entity_id from sport.player pl LEFT JOIN club.person pe ON pl.member_no = pe.member_no WHERE 1=1 AND pe.FIRST_NAME='Eddison' AND pe.LAST_NAME='Ambarzumjan') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 7,help.entity_id,'player','Aufwandsentschädigung',1,TIMESTAMPTZ '2019-05-01 00:00:00',TIMESTAMPTZ '2019-09-01 00:00:00',1,3,190,NULL,FALSE FROM help;
WITH help as (SELECT pl.player_id as entity_id from sport.player pl LEFT JOIN club.person pe ON pl.member_no = pe.member_no WHERE 1=1 AND pe.FIRST_NAME='Eddison' AND pe.LAST_NAME='Ambarzumjan') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 7,help.entity_id,'player','Aufwandsentschädigung',1,TIMESTAMPTZ '2020-05-01 00:00:00',TIMESTAMPTZ '2020-09-01 00:00:00',1,3,190,NULL,FALSE FROM help;
WITH help as (SELECT pl.player_id as entity_id from sport.player pl LEFT JOIN club.person pe ON pl.member_no = pe.member_no WHERE 1=1 AND pe.FIRST_NAME='Matvey' AND pe.LAST_NAME='Khomentovsky') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 7,help.entity_id,'player','Aufwandsentschädigung',1,TIMESTAMPTZ '2019-05-01 00:00:00',TIMESTAMPTZ '2019-09-01 00:00:00',1,3,190,NULL,FALSE FROM help;
WITH help as (SELECT pl.player_id as entity_id from sport.player pl LEFT JOIN club.person pe ON pl.member_no = pe.member_no WHERE 1=1 AND pe.FIRST_NAME='Matvey' AND pe.LAST_NAME='Khomentovsky') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 7,help.entity_id,'player','Aufwandsentschädigung',1,TIMESTAMPTZ '2020-05-01 00:00:00',TIMESTAMPTZ '2020-09-01 00:00:00',1,3,190,NULL,FALSE FROM help;
WITH help as (SELECT pl.player_id as entity_id from sport.player pl LEFT JOIN club.person pe ON pl.member_no = pe.member_no WHERE 1=1 AND pe.FIRST_NAME='Konstantin' AND pe.LAST_NAME='Barth') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 7,help.entity_id,'player','Spielergehalt',1,TIMESTAMPTZ '2019-01-01 00:00:00',TIMESTAMPTZ '2020-01-01 00:00:00',1,3,NULL,1050,TRUE FROM help;
WITH help as (SELECT pl.player_id as entity_id from sport.player pl LEFT JOIN club.person pe ON pl.member_no = pe.member_no WHERE 1=1 AND pe.FIRST_NAME='Konstantin' AND pe.LAST_NAME='Barth') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 7,help.entity_id,'player','Spielergehalt',1,TIMESTAMPTZ '2020-01-01 00:00:00',TIMESTAMPTZ '2021-01-01 00:00:00',1,3,NULL,1050,TRUE FROM help;
WITH help as (SELECT pl.player_id as entity_id from sport.player pl LEFT JOIN club.person pe ON pl.member_no = pe.member_no WHERE 1=1 AND pe.FIRST_NAME='Florian' AND pe.LAST_NAME='Grassl') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 7,help.entity_id,'player','Spielergehalt',1,TIMESTAMPTZ '2019-01-01 00:00:00',TIMESTAMPTZ '2020-01-01 00:00:00',1,3,1000,NULL,FALSE FROM help;
WITH help as (SELECT pl.player_id as entity_id from sport.player pl LEFT JOIN club.person pe ON pl.member_no = pe.member_no WHERE 1=1 AND pe.FIRST_NAME='Florian' AND pe.LAST_NAME='Grassl') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 7,help.entity_id,'player','Spielergehalt',1,TIMESTAMPTZ '2020-01-01 00:00:00',TIMESTAMPTZ '2021-01-01 00:00:00',1,3,1000,NULL,FALSE FROM help;
WITH help as (SELECT pl.player_id as entity_id from sport.player pl LEFT JOIN club.person pe ON pl.member_no = pe.member_no WHERE 1=1 AND pe.FIRST_NAME='Eddison' AND pe.LAST_NAME='Ambarzumjan') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 7,help.entity_id,'player','Spielergehalt',1,TIMESTAMPTZ '2019-01-01 00:00:00',TIMESTAMPTZ '2020-01-01 00:00:00',1,3,NULL,2450,TRUE FROM help;
WITH help as (SELECT pl.player_id as entity_id from sport.player pl LEFT JOIN club.person pe ON pl.member_no = pe.member_no WHERE 1=1 AND pe.FIRST_NAME='Eddison' AND pe.LAST_NAME='Ambarzumjan') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 7,help.entity_id,'player','Spielergehalt',1,TIMESTAMPTZ '2020-01-01 00:00:00',TIMESTAMPTZ '2021-01-01 00:00:00',1,3,NULL,2450,TRUE FROM help;
WITH help as (SELECT pl.player_id as entity_id from sport.player pl LEFT JOIN club.person pe ON pl.member_no = pe.member_no WHERE 1=1 AND pe.FIRST_NAME='Simon' AND pe.LAST_NAME='Walter') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 7,help.entity_id,'player','Hallenstunden',3,TIMESTAMPTZ '2020-01-01 00:00:00',TIMESTAMPTZ '2020-04-20 00:00:00',15,4,14,NULL,FALSE FROM help;
WITH help as (SELECT pl.player_id as entity_id from sport.player pl LEFT JOIN club.person pe ON pl.member_no = pe.member_no WHERE 1=1 AND pe.FIRST_NAME='Simon' AND pe.LAST_NAME='Walter') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 7,help.entity_id,'player','Hallenstunden',3,TIMESTAMPTZ '2020-09-22 00:00:00',TIMESTAMPTZ '2021-04-20 00:00:00',25,4,14,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Damen 30' AND SEASON='Sommer 2020') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 10,help.entity_id,'team','Saisonfinale',2,TIMESTAMPTZ '2020-08-20 00:00:00',TIMESTAMPTZ '2020-08-30 00:00:00',1,3,1500,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Damen' AND SEASON='Sommer 2020') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 3,help.entity_id,'team','Damen Trainerdoppelstunde Winter 2019/2020',2,TIMESTAMPTZ '2019-09-21 00:00:00',TIMESTAMPTZ '2020-04-01 00:00:00',50,1,44,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Damen' AND SEASON='Sommer 2020') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 3,help.entity_id,'team','Damen Trainerstunde Sommer 2020',2,TIMESTAMPTZ '2020-04-01 00:00:00',TIMESTAMPTZ '2020-09-22 00:00:00',11,1,44,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Damen' AND SEASON='Sommer 2021') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 3,help.entity_id,'team','Damen Trainerstunde Winter 2020/2021',2,TIMESTAMPTZ '2020-09-22 00:00:00',TIMESTAMPTZ '2021-04-01 00:00:00',25,1,44,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Damen 30' AND SEASON='Sommer 2020') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 11,help.entity_id,'team','Mannschaftsnenngebühr Regionalliga',4,TIMESTAMPTZ '2020-05-01 00:00:00',TIMESTAMPTZ '2020-09-01 00:00:00',1,1,150,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Herren' AND SEASON='Sommer 2020') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 11,help.entity_id,'team','Mannschaftsnenngebühr Landesliga',4,TIMESTAMPTZ '2020-05-01 00:00:00',TIMESTAMPTZ '2020-09-01 00:00:00',1,1,57,NULL,FALSE FROM help;
WITH help as (SELECT team.team_id as entity_id from sport.team WHERE 1=1 AND TEAM_NAME='Damen' AND SEASON='Sommer 2020') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 11,help.entity_id,'team','Mannschaftsnenngebühr Bezirksliga',4,TIMESTAMPTZ '2020-05-01 00:00:00',TIMESTAMPTZ '2020-09-01 00:00:00',1,1,50,NULL,FALSE FROM help;
WITH help as (SELECT pl.player_id as entity_id from sport.player pl LEFT JOIN club.person pe ON pl.member_no = pe.member_no WHERE 1=1 AND pe.FIRST_NAME='Alexander' AND pe.LAST_NAME='Satschko') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 7,help.entity_id,'player','Spielergehalt',1,TIMESTAMPTZ '2020-05-01 00:00:00',TIMESTAMPTZ '2020-09-01 00:00:00',1,3,NULL,6000,TRUE FROM help;
WITH help as (SELECT pl.player_id as entity_id from sport.player pl LEFT JOIN club.person pe ON pl.member_no = pe.member_no WHERE 1=1 AND pe.FIRST_NAME='Nikolas' AND pe.LAST_NAME='Holzen') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 7,help.entity_id,'player','Spielergehalt',1,TIMESTAMPTZ '2020-05-01 00:00:00',TIMESTAMPTZ '2020-09-01 00:00:00',1,3,NULL,2800,TRUE FROM help;
WITH help as (SELECT pl.player_id as entity_id from sport.player pl LEFT JOIN club.person pe ON pl.member_no = pe.member_no WHERE 1=1 AND pe.FIRST_NAME='Maximilian' AND pe.LAST_NAME='Schmuck') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 7,help.entity_id,'player','Spielergehalt',1,TIMESTAMPTZ '2020-05-01 00:00:00',TIMESTAMPTZ '2020-09-01 00:00:00',1,3,NULL,2800,TRUE FROM help;
WITH help as (SELECT pl.player_id as entity_id from sport.player pl LEFT JOIN club.person pe ON pl.member_no = pe.member_no WHERE 1=1 AND pe.FIRST_NAME='Eddison' AND pe.LAST_NAME='Ambarzumjan') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 4,help.entity_id,'player','Sparingspartner',3,TIMESTAMPTZ '2020-04-01 00:00:00',TIMESTAMPTZ '2020-10-01 00:00:00',1,5,NULL,125,TRUE FROM help;
WITH help as (SELECT pl.player_id as entity_id from sport.player pl LEFT JOIN club.person pe ON pl.member_no = pe.member_no WHERE 1=1 AND pe.FIRST_NAME='Simon' AND pe.LAST_NAME='Walter') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 4,help.entity_id,'player','Sparingspartner',3,TIMESTAMPTZ '2020-04-01 00:00:00',TIMESTAMPTZ '2020-10-01 00:00:00',1,5,NULL,125,TRUE FROM help;
WITH help as (SELECT pl.player_id as entity_id from sport.player pl LEFT JOIN club.person pe ON pl.member_no = pe.member_no WHERE 1=1 AND pe.FIRST_NAME='Konstantin' AND pe.LAST_NAME='Barth') INSERT INTO sport.benefit (BENEFIT_TYPE_ID,ENTITY_ID,ENTITY,DESCRIPTION,BENEFIT_GRADE_ID,VALID_FROM,VALID_TO,COUNT,AMOUNT_ID,VALUE,CAP_SUM_VALUE,IS_CLAIMABLE) SELECT 4,help.entity_id,'player','Sparingspartner',3,TIMESTAMPTZ '2020-04-01 00:00:00',TIMESTAMPTZ '2020-10-01 00:00:00',1,5,NULL,125,TRUE FROM help;


/*
-- Im Zeitraum (hier '2019-01-01 00:00:00' bis '2012-01-01 00:00:00') soll pro Spieler ermittelt werden welche Benefits ein Spieler genießt
-- Parameter müssen sein:
-- 1. Spieler (member_no)
-- 2. Zeitraum (von bis: z.B. Geschäftsjahr und Sommer + Wintersaison als Voreinstellungen: View?)
--set {0}:=2;
--set TIMESTAMPTZ '2019-09-21 00:00:00':=TIMESTAMPTZ '2019-01-01 00:00:00';
--set TIMESTAMPTZ '2020-09-22 00:00:00':=TIMESTAMPTZ '2020-01-01 00:00:00';
SELECT
	person.first_name,
	person.last_name,
	team.team_name,
    basis.member_no,
    basis.description,
    basis.sum_part_time,
	benefit_grade.benefit_grade_name,
    CASE WHEN basis.is_claimable THEN
        basis.sum_claim
    ELSE
        basis.sum_part_time
    END AS sum_claim
FROM (
    SELECT
        p.member_no,
        b.description, -- Benefits die vom Betrachtungszeitraum abweichen sollen nur anteilig eingerechnet werden.
    b.benefit_grade_id,
	sport.f_date_period_part (TIMESTAMPTZ '2019-09-21 00:00:00',
            TIMESTAMPTZ '2020-09-22 00:00:00',
            b.valid_from,
            b.valid_to) * CASE WHEN b.value IS NULL THEN
            b.cap_sum_value
        ELSE
            b.count * b.value
END / cnt_team_members AS sum_part_time,
c.value / cnt_team_members AS sum_claim,
b.is_claimable
FROM
    sport.benefit b -- Die Summe der tatsächlich eingeforderten Benefitsumme pro benefit_id
    LEFT JOIN (
        SELECT
            c.benefit_id,
            SUM(c.value) AS value
        FROM
            sport.claim c
        WHERE
            1 = 1
            AND c.created_at >= TIMESTAMPTZ '2019-09-21 00:00:00'
            AND c.created_at < TIMESTAMPTZ '2020-09-22 00:00:00'
        GROUP BY
            c.benefit_id) c ON c.benefit_id = b.benefit_id
    LEFT JOIN sport.team t ON b.entity_id = t.team_id
    LEFT JOIN sport.team_members tm ON t.team_id = tm.team_id
    LEFT JOIN (
        SELECT
            tm.team_id,
            COUNT(*) AS cnt_team_members
        FROM
            sport.team_members tm
        WHERE
            1 = 1
            AND tm.is_main_team = TRUE
        GROUP BY
            team_id) tm_count ON tm.team_id = tm_count.team_id
    LEFT JOIN sport.player p ON tm.player_id = p.player_id
    LEFT JOIN club.person pers ON p.member_no = p.member_no
WHERE
    1 = 1
    AND entity = 'team'
    AND ((b.valid_from <= TIMESTAMPTZ '2019-09-21 00:00:00'
            AND b.valid_to > TIMESTAMPTZ '2019-09-21 00:00:00')
        OR (b.valid_from < TIMESTAMPTZ '2020-09-22 00:00:00'
            AND b.valid_to >= TIMESTAMPTZ '2020-09-22 00:00:00')
        OR (b.valid_from >= TIMESTAMPTZ '2019-09-21 00:00:00'
            AND b.valid_from < TIMESTAMPTZ '2020-09-22 00:00:00'))
UNION
-- Benefits pro Einzelspieler
SELECT
    p.member_no,
    b.description, -- Benefits die vom Betrachtungszeitraum abweichen sollen nur anteilig eingerechnet werden.
   b.benefit_grade_id,
	sport.f_date_period_part (TIMESTAMPTZ '2019-09-21 00:00:00',
        TIMESTAMPTZ '2020-09-22 00:00:00',
        b.valid_from,
        b.valid_to) * CASE WHEN b.value IS NULL THEN
        b.cap_sum_value
    ELSE
        b.count * b.value
    END AS sum_part_time,
    c.value AS sum_claim,
    b.is_claimable
FROM
    sport.benefit b
    LEFT JOIN sport.player p ON b.entity_id = p.player_id -- Die Summe der tatsächlich eingeforderten Benefitsumme pro benefit_id
    LEFT JOIN (
        SELECT
            c.benefit_id,
            SUM(c.value) AS value
        FROM
            sport.claim c
        WHERE
            1 = 1
            AND c.created_at >= TIMESTAMPTZ '2019-09-21 00:00:00'
            AND c.created_at < TIMESTAMPTZ '2020-09-22 00:00:00'
        GROUP BY
            c.benefit_id) c ON c.benefit_id = b.benefit_id
    LEFT JOIN club.person pers ON p.member_no = p.member_no
WHERE
    1 = 1
    AND entity = 'player'
    AND ((b.valid_from <= TIMESTAMPTZ '2019-09-21 00:00:00'
            AND b.valid_to > TIMESTAMPTZ '2019-09-21 00:00:00')
        OR (b.valid_from < TIMESTAMPTZ '2020-09-22 00:00:00'
            AND b.valid_to >= TIMESTAMPTZ '2020-09-22 00:00:00')
        OR (b.valid_from >= TIMESTAMPTZ '2019-09-21 00:00:00'
            AND b.valid_from < TIMESTAMPTZ '2020-09-22 00:00:00'))) basis
			LEFT JOIN club.person ON person.member_no = basis.member_no
			LEFT JOIN sport.player ON person.member_no = player.member_no
			LEFT JOIN sport.team_members ON  player.player_id = team_members.player_id
			LEFT JOIN sport.team ON team_members.team_id = team.team_id
			LEFT JOIN sport.benefit_grade ON basis.benefit_grade_id = benefit_grade.benefit_grade_id
			WHERE team.valid_from >= TIMESTAMPTZ '2019-09-21 00:00:00'
			AND team.valid_to < TIMESTAMPTZ '2020-09-22 00:00:00'
order by 1
*/
